# This file specifies your Python application's runtime configuration.
# See https://cloud.google.com/appengine/docs/managed-vms/python/runtime
# for details.

runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

#[START cloudsql_settings]
beta_settings:
    # If using Cloud SQL, uncomment and set this value to the Cloud SQL
    # connection name, e.g.
    #   "project:region:cloudsql-instance"
    # You must also update the values in config.py.
    #
    cloud_sql_instances: "cloudsql-instance"
#[END cloudsql_settings]
